# Generated by Django 3.0.5 on 2020-04-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CdC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='observertion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='log',
            field=models.ManyToManyField(blank=True, null=True, to='CdC.carlog'),
        ),
        migrations.AlterField(
            model_name='car',
            name='position',
            field=models.CharField(blank=True, choices=[('Patio', 'Patio'), ('Morumbi', 'Morumbi'), ('Butantã', 'Butantã'), ('Pinheiros', 'Pinheiros'), ('Faria', 'Faria'), ('Fradique', 'Fradique'), ('Oscar', 'Oscar'), ('Paulista', 'Paulista'), ('Higeanopolis', 'Higeanopolis'), ('Republica', 'Republica'), ('Luz', 'Luz')], max_length=30, null=True, verbose_name='Localização'),
        ),
        migrations.AlterField(
            model_name='carlog',
            name='destino',
            field=models.CharField(choices=[('Patio', 'Patio'), ('Morumbi', 'Morumbi'), ('Butantã', 'Butantã'), ('Pinheiros', 'Pinheiros'), ('Faria', 'Faria'), ('Fradique', 'Fradique'), ('Oscar', 'Oscar'), ('Paulista', 'Paulista'), ('Higeanopolis', 'Higeanopolis'), ('Republica', 'Republica'), ('Luz', 'Luz')], max_length=30),
        ),
        migrations.AlterField(
            model_name='carlog',
            name='origem',
            field=models.CharField(choices=[('Patio', 'Patio'), ('Morumbi', 'Morumbi'), ('Butantã', 'Butantã'), ('Pinheiros', 'Pinheiros'), ('Faria', 'Faria'), ('Fradique', 'Fradique'), ('Oscar', 'Oscar'), ('Paulista', 'Paulista'), ('Higeanopolis', 'Higeanopolis'), ('Republica', 'Republica'), ('Luz', 'Luz')], max_length=30),
        ),
        migrations.AlterField(
            model_name='equipament',
            name='log',
            field=models.ManyToManyField(blank=True, null=True, to='CdC.log'),
        ),
        migrations.AlterField(
            model_name='equipament',
            name='position',
            field=models.CharField(blank=True, choices=[('Patio', 'Patio'), ('Morumbi', 'Morumbi'), ('Butantã', 'Butantã'), ('Pinheiros', 'Pinheiros'), ('Faria', 'Faria'), ('Fradique', 'Fradique'), ('Oscar', 'Oscar'), ('Paulista', 'Paulista'), ('Higeanopolis', 'Higeanopolis'), ('Republica', 'Republica'), ('Luz', 'Luz')], max_length=30, null=True, verbose_name='Localização'),
        ),
        migrations.AlterField(
            model_name='log',
            name='destino',
            field=models.CharField(choices=[('Patio', 'Patio'), ('Morumbi', 'Morumbi'), ('Butantã', 'Butantã'), ('Pinheiros', 'Pinheiros'), ('Faria', 'Faria'), ('Fradique', 'Fradique'), ('Oscar', 'Oscar'), ('Paulista', 'Paulista'), ('Higeanopolis', 'Higeanopolis'), ('Republica', 'Republica'), ('Luz', 'Luz')], max_length=30),
        ),
        migrations.AlterField(
            model_name='log',
            name='origem',
            field=models.CharField(choices=[('Patio', 'Patio'), ('Morumbi', 'Morumbi'), ('Butantã', 'Butantã'), ('Pinheiros', 'Pinheiros'), ('Faria', 'Faria'), ('Fradique', 'Fradique'), ('Oscar', 'Oscar'), ('Paulista', 'Paulista'), ('Higeanopolis', 'Higeanopolis'), ('Republica', 'Republica'), ('Luz', 'Luz')], max_length=30),
        ),
    ]
