# Generated by Django 3.0.5 on 2020-04-29 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CdC', '0007_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
