# Generated by Django 3.0.6 on 2020-05-30 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('type_of_log', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('destiny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DestinoLog', to='CdC.Place')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrigemLog', to='CdC.Place')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, verbose_name='Codigo do Equipamento')),
                ('name', models.CharField(max_length=244, verbose_name='Nome')),
                ('nickName', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apelido')),
                ('date_calibration', models.DateField(verbose_name='Data de Calibração')),
                ('validity_time', models.IntegerField(blank=True, null=True, verbose_name='Meses de validade')),
                ('date_validity', models.DateField(blank=True, null=True, verbose_name='Data de validade se preenche automatico se deixado em branco')),
                ('in_calibration', models.IntegerField()),
                ('where', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='CdC.Place')),
            ],
        ),
        migrations.CreateModel(
            name='Carlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licensePlate', models.CharField(max_length=15, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('destiny', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Destino', to='CdC.Place')),
                ('origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Origem', to='CdC.Place')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licensePlate', models.CharField(max_length=8, unique=True, verbose_name='Placa')),
                ('name', models.CharField(max_length=100, verbose_name='Modelo')),
                ('in_use', models.BooleanField(null=True)),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('where', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CdC.Place')),
            ],
        ),
    ]
