# Generated by Django 3.0.6 on 2020-05-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=8, unique=True, verbose_name='Placa')),
                ('nome', models.CharField(max_length=100, verbose_name='Modelo')),
                ('position', models.CharField(blank=True, max_length=30, null=True, verbose_name='Localização')),
                ('in_use', models.CharField(blank=True, max_length=15, null=True, verbose_name='Utilizador')),
            ],
        ),
        migrations.CreateModel(
            name='carlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(blank=True, max_length=30, null=True)),
                ('origem', models.CharField(max_length=30)),
                ('destino', models.CharField(blank=True, max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('responsible', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Equipament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True, verbose_name='Codigo do Equipamento')),
                ('nome', models.CharField(max_length=244, verbose_name='Nome')),
                ('apelido', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apelido')),
                ('position', models.CharField(blank=True, max_length=30, null=True, verbose_name='Localização')),
                ('date_calibration', models.DateField(verbose_name='Data de Calibração')),
                ('validity_time', models.IntegerField(blank=True, null=True, verbose_name='Meses de validade')),
                ('date_validity', models.DateField(blank=True, null=True, verbose_name='Data de validade se preenche automatico se deixado em branco')),
                ('in_calibration', models.IntegerField()),
            ],
            options={
                'permissions': [('can_move', 'Pode mover equipamentos'), ('can_receive', 'Pode receber equipamentos de calibração'), ('can_see_log', 'Pode ver os logs')],
            },
        ),
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('origem', models.CharField(max_length=30)),
                ('destino', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('responsible', models.CharField(max_length=10)),
                ('observation', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('viewName', models.CharField(max_length=30)),
            ],
        ),
    ]
