# Generated by Django 3.0.5 on 2020-04-29 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.ImageField(upload_to='')),
                ('origem', models.CharField(max_length=30)),
                ('destino', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('responsible', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.ImageField(upload_to='')),
                ('origem', models.CharField(max_length=30)),
                ('destino', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('responsible', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Equipament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True, verbose_name='Codigo do Equipamento')),
                ('nome', models.CharField(max_length=244, verbose_name='Nome')),
                ('apelido', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apelido')),
                ('position', models.CharField(blank=True, max_length=30, null=True, verbose_name='Localização')),
                ('date_calibration', models.DateField(verbose_name='Data de Calibração')),
                ('date_validity', models.DateField(blank=True, null=True, verbose_name='Data de valida, se prenche com 1 ano se não informado')),
                ('in_calibration', models.IntegerField()),
                ('log', models.ManyToManyField(to='CdC.log')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=8, unique=True, verbose_name='Placa')),
                ('nome', models.CharField(max_length=100, verbose_name='Modelo')),
                ('position', models.CharField(blank=True, max_length=30, null=True, verbose_name='Localização')),
                ('log', models.ManyToManyField(to='CdC.carlog')),
            ],
        ),
    ]
