<<<<<<< HEAD:CdC/migrations/0007_profile.py
# Generated by Django 3.0.5 on 2020-04-29 23:49
=======
# Generated by Django 3.0.6 on 2020-05-26 01:11
>>>>>>> develop:CdC/migrations/0003_additionalinfo.py

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
<<<<<<< HEAD:CdC/migrations/0007_profile.py
        ('CdC', '0006_auto_20200429_2018'),
=======
        ('CdC', '0002_auto_20200525_2123'),
>>>>>>> develop:CdC/migrations/0003_additionalinfo.py
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD:CdC/migrations/0007_profile.py
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(blank=True, choices=[('Patio', 'Patio'), ('Morumbi', 'Morumbi'), ('Butantã', 'Butantã'), ('Pinheiros', 'Pinheiros'), ('Faria Lima', 'Faria Lima'), ('Fradique', 'Fradique'), ('Oscar Freire', 'Oscar Freire'), ('Paulista', 'Paulista'), ('Higeanopolis', 'Higeanopolis'), ('Republica', 'Republica'), ('Luz', 'Luz')], max_length=30, null=True, verbose_name='Estação de Trabalho')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
=======
            name='AdditionalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workPlace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CdC.Place')),
>>>>>>> develop:CdC/migrations/0003_additionalinfo.py
            ],
        ),
    ]
