# Generated by Django 3.0.6 on 2020-05-26 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CdC', '0003_additionalinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='observation',
        ),
        migrations.AlterField(
            model_name='car',
            name='where',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='CdC.Place'),
        ),
        migrations.AlterField(
            model_name='carlog',
            name='destiny',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Destino', to='CdC.Place'),
        ),
        migrations.AlterField(
            model_name='carlog',
            name='licensePlate',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='carlog',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Origem', to='CdC.Place'),
        ),
        migrations.AlterField(
            model_name='carlog',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='where',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='CdC.Place'),
        ),
        migrations.AlterField(
            model_name='log',
            name='destiny',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DestinoLog', to='CdC.Place'),
        ),
        migrations.AlterField(
            model_name='log',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrigemLog', to='CdC.Place'),
        ),
        migrations.AlterField(
            model_name='log',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AdditionalInfo',
        ),
    ]
