# Generated by Django 3.0.6 on 2020-05-26 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CdC', '0004_auto_20200526_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='car',
            name='in_use',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='where',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CdC.Place'),
        ),
    ]
