# Generated by Django 3.0.5 on 2020-04-29 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CdC', '0005_auto_20200429_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='position',
            field=models.CharField(blank=True, choices=[('Patio', 'Patio'), ('Morumbi', 'Morumbi'), ('Butantã', 'Butantã'), ('Pinheiros', 'Pinheiros'), ('Faria Lima', 'Faria Lima'), ('Fradique', 'Fradique'), ('Oscar Freire', 'Oscar Freire'), ('Paulista', 'Paulista'), ('Higeanopolis', 'Higeanopolis'), ('Republica', 'Republica'), ('Luz', 'Luz')], max_length=30, null=True, verbose_name='Localização'),
        ),
        migrations.AlterField(
            model_name='carlog',
            name='destino',
            field=models.CharField(choices=[('Patio', 'Patio'), ('Morumbi', 'Morumbi'), ('Butantã', 'Butantã'), ('Pinheiros', 'Pinheiros'), ('Faria Lima', 'Faria Lima'), ('Fradique', 'Fradique'), ('Oscar Freire', 'Oscar Freire'), ('Paulista', 'Paulista'), ('Higeanopolis', 'Higeanopolis'), ('Republica', 'Republica'), ('Luz', 'Luz')], max_length=30),
        ),
        migrations.AlterField(
            model_name='carlog',
            name='origem',
            field=models.CharField(choices=[('Patio', 'Patio'), ('Morumbi', 'Morumbi'), ('Butantã', 'Butantã'), ('Pinheiros', 'Pinheiros'), ('Faria Lima', 'Faria Lima'), ('Fradique', 'Fradique'), ('Oscar Freire', 'Oscar Freire'), ('Paulista', 'Paulista'), ('Higeanopolis', 'Higeanopolis'), ('Republica', 'Republica'), ('Luz', 'Luz')], max_length=30),
        ),
        migrations.AlterField(
            model_name='equipament',
            name='position',
            field=models.CharField(blank=True, choices=[('Patio', 'Patio'), ('Morumbi', 'Morumbi'), ('Butantã', 'Butantã'), ('Pinheiros', 'Pinheiros'), ('Faria Lima', 'Faria Lima'), ('Fradique', 'Fradique'), ('Oscar Freire', 'Oscar Freire'), ('Paulista', 'Paulista'), ('Higeanopolis', 'Higeanopolis'), ('Republica', 'Republica'), ('Luz', 'Luz')], max_length=30, null=True, verbose_name='Localização'),
        ),
        migrations.AlterField(
            model_name='log',
            name='codigo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='log',
            name='destino',
            field=models.CharField(choices=[('Patio', 'Patio'), ('Morumbi', 'Morumbi'), ('Butantã', 'Butantã'), ('Pinheiros', 'Pinheiros'), ('Faria Lima', 'Faria Lima'), ('Fradique', 'Fradique'), ('Oscar Freire', 'Oscar Freire'), ('Paulista', 'Paulista'), ('Higeanopolis', 'Higeanopolis'), ('Republica', 'Republica'), ('Luz', 'Luz')], max_length=30),
        ),
        migrations.AlterField(
            model_name='log',
            name='origem',
            field=models.CharField(choices=[('Patio', 'Patio'), ('Morumbi', 'Morumbi'), ('Butantã', 'Butantã'), ('Pinheiros', 'Pinheiros'), ('Faria Lima', 'Faria Lima'), ('Fradique', 'Fradique'), ('Oscar Freire', 'Oscar Freire'), ('Paulista', 'Paulista'), ('Higeanopolis', 'Higeanopolis'), ('Republica', 'Republica'), ('Luz', 'Luz')], max_length=30),
        ),
    ]
