# Generated by Django 3.0.5 on 2020-04-30 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CdC', '0008_delete_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipament',
            options={'permissions': [('can_move', 'Pode mover equipamentos'), ('can_receive', 'Pode receber equipamentos de calibração'), ('can_see_log', 'Pode ver os logs')]},
        ),
    ]
