# Generated by Django 3.0.5 on 2020-04-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CdC', '0009_auto_20200429_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='position',
            field=models.CharField(blank=True, choices=[('Patio', 'Patio'), ('Morumbi', 'Morumbi'), ('Butantã', 'Butantã'), ('Pinheiros', 'Pinheiros'), ('Faria Lima', 'Faria Lima'), ('Fradique Coutinho', 'Fradique Coutinho'), ('Oscar Freire', 'Oscar Freire'), ('Paulista', 'Paulista'), ('Higeanopolis', 'Higeanopolis'), ('Republica', 'Republica'), ('Luz', 'Luz'), ('Calibração', 'Calibração')], max_length=30, null=True, verbose_name='Localização'),
        ),
        migrations.AlterField(
            model_name='carlog',
            name='destino',
            field=models.CharField(choices=[('Patio', 'Patio'), ('Morumbi', 'Morumbi'), ('Butantã', 'Butantã'), ('Pinheiros', 'Pinheiros'), ('Faria Lima', 'Faria Lima'), ('Fradique Coutinho', 'Fradique Coutinho'), ('Oscar Freire', 'Oscar Freire'), ('Paulista', 'Paulista'), ('Higeanopolis', 'Higeanopolis'), ('Republica', 'Republica'), ('Luz', 'Luz'), ('Calibração', 'Calibração')], max_length=30),
        ),
        migrations.AlterField(
            model_name='carlog',
            name='origem',
            field=models.CharField(choices=[('Patio', 'Patio'), ('Morumbi', 'Morumbi'), ('Butantã', 'Butantã'), ('Pinheiros', 'Pinheiros'), ('Faria Lima', 'Faria Lima'), ('Fradique Coutinho', 'Fradique Coutinho'), ('Oscar Freire', 'Oscar Freire'), ('Paulista', 'Paulista'), ('Higeanopolis', 'Higeanopolis'), ('Republica', 'Republica'), ('Luz', 'Luz'), ('Calibração', 'Calibração')], max_length=30),
        ),
        migrations.AlterField(
            model_name='equipament',
            name='position',
            field=models.CharField(blank=True, choices=[('Patio', 'Patio'), ('Morumbi', 'Morumbi'), ('Butantã', 'Butantã'), ('Pinheiros', 'Pinheiros'), ('Faria Lima', 'Faria Lima'), ('Fradique Coutinho', 'Fradique Coutinho'), ('Oscar Freire', 'Oscar Freire'), ('Paulista', 'Paulista'), ('Higeanopolis', 'Higeanopolis'), ('Republica', 'Republica'), ('Luz', 'Luz'), ('Calibração', 'Calibração')], max_length=30, null=True, verbose_name='Localização'),
        ),
        migrations.AlterField(
            model_name='log',
            name='destino',
            field=models.CharField(choices=[('Patio', 'Patio'), ('Morumbi', 'Morumbi'), ('Butantã', 'Butantã'), ('Pinheiros', 'Pinheiros'), ('Faria Lima', 'Faria Lima'), ('Fradique Coutinho', 'Fradique Coutinho'), ('Oscar Freire', 'Oscar Freire'), ('Paulista', 'Paulista'), ('Higeanopolis', 'Higeanopolis'), ('Republica', 'Republica'), ('Luz', 'Luz'), ('Calibração', 'Calibração')], max_length=30),
        ),
        migrations.AlterField(
            model_name='log',
            name='origem',
            field=models.CharField(choices=[('Patio', 'Patio'), ('Morumbi', 'Morumbi'), ('Butantã', 'Butantã'), ('Pinheiros', 'Pinheiros'), ('Faria Lima', 'Faria Lima'), ('Fradique Coutinho', 'Fradique Coutinho'), ('Oscar Freire', 'Oscar Freire'), ('Paulista', 'Paulista'), ('Higeanopolis', 'Higeanopolis'), ('Republica', 'Republica'), ('Luz', 'Luz'), ('Calibração', 'Calibração')], max_length=30),
        ),
    ]
