# Generated by Django 3.0.5 on 2020-04-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CdC', '0011_auto_20200430_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='observation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
