# Generated by Django 3.0.5 on 2020-05-01 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CdC', '0013_auto_20200430_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='in_use',
            field=models.IntegerField(null=True),
        ),
    ]
