# Generated by Django 3.0.5 on 2020-05-01 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CdC', '0014_car_in_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='position',
            field=models.CharField(blank=True, choices=[('Patio', 'Patio'), ('Morumbi', 'Morumbi'), ('Butantã', 'Butantã'), ('Pinheiros', 'Pinheiros'), ('Faria Lima', 'Faria Lima'), ('Fradique Coutinho', 'Fradique Coutinho'), ('Oscar Freire', 'Oscar Freire'), ('Paulista', 'Paulista'), ('Higeanopolis', 'Higeanopolis'), ('Republica', 'Republica'), ('Luz', 'Luz'), ('Calibração', 'Calibração'), ('Em uso', 'Em uso')], max_length=30, null=True, verbose_name='Localização'),
        ),
    ]
