# Generated by Django 3.0.5 on 2020-05-01 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CdC', '0016_auto_20200501_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='position',
            field=models.CharField(blank=True, choices=[('Patio', 'Patio'), ('Morumbi', 'Morumbi'), ('Butantã', 'Butantã'), ('Pinheiros', 'Pinheiros'), ('Faria Lima', 'Faria Lima'), ('Fradique Coutinho', 'Fradique Coutinho'), ('Oscar Freire', 'Oscar Freire'), ('Paulista', 'Paulista'), ('higienopolis', 'higienopolis'), ('Republica', 'Republica'), ('Luz', 'Luz'), ('Calibração', 'Calibração'), ('Em uso', 'Em uso')], max_length=30, null=True, verbose_name='Localização'),
        ),
        migrations.AlterField(
            model_name='carlog',
            name='destino',
            field=models.CharField(choices=[('Patio', 'Patio'), ('Morumbi', 'Morumbi'), ('Butantã', 'Butantã'), ('Pinheiros', 'Pinheiros'), ('Faria Lima', 'Faria Lima'), ('Fradique Coutinho', 'Fradique Coutinho'), ('Oscar Freire', 'Oscar Freire'), ('Paulista', 'Paulista'), ('higienopolis', 'higienopolis'), ('Republica', 'Republica'), ('Luz', 'Luz'), ('Calibração', 'Calibração'), ('Base', 'Base')], max_length=30),
        ),
        migrations.AlterField(
            model_name='carlog',
            name='origem',
            field=models.CharField(choices=[('Patio', 'Patio'), ('Morumbi', 'Morumbi'), ('Butantã', 'Butantã'), ('Pinheiros', 'Pinheiros'), ('Faria Lima', 'Faria Lima'), ('Fradique Coutinho', 'Fradique Coutinho'), ('Oscar Freire', 'Oscar Freire'), ('Paulista', 'Paulista'), ('higienopolis', 'higienopolis'), ('Republica', 'Republica'), ('Luz', 'Luz'), ('Calibração', 'Calibração'), ('Base', 'Base')], max_length=30),
        ),
        migrations.AlterField(
            model_name='equipament',
            name='position',
            field=models.CharField(blank=True, choices=[('Patio', 'Patio'), ('Morumbi', 'Morumbi'), ('Butantã', 'Butantã'), ('Pinheiros', 'Pinheiros'), ('Faria Lima', 'Faria Lima'), ('Fradique Coutinho', 'Fradique Coutinho'), ('Oscar Freire', 'Oscar Freire'), ('Paulista', 'Paulista'), ('higienopolis', 'higienopolis'), ('Republica', 'Republica'), ('Luz', 'Luz'), ('Calibração', 'Calibração'), ('Base', 'Base')], max_length=30, null=True, verbose_name='Localização'),
        ),
        migrations.AlterField(
            model_name='log',
            name='destino',
            field=models.CharField(choices=[('Patio', 'Patio'), ('Morumbi', 'Morumbi'), ('Butantã', 'Butantã'), ('Pinheiros', 'Pinheiros'), ('Faria Lima', 'Faria Lima'), ('Fradique Coutinho', 'Fradique Coutinho'), ('Oscar Freire', 'Oscar Freire'), ('Paulista', 'Paulista'), ('higienopolis', 'higienopolis'), ('Republica', 'Republica'), ('Luz', 'Luz'), ('Calibração', 'Calibração'), ('Base', 'Base')], max_length=30),
        ),
        migrations.AlterField(
            model_name='log',
            name='origem',
            field=models.CharField(choices=[('Patio', 'Patio'), ('Morumbi', 'Morumbi'), ('Butantã', 'Butantã'), ('Pinheiros', 'Pinheiros'), ('Faria Lima', 'Faria Lima'), ('Fradique Coutinho', 'Fradique Coutinho'), ('Oscar Freire', 'Oscar Freire'), ('Paulista', 'Paulista'), ('higienopolis', 'higienopolis'), ('Republica', 'Republica'), ('Luz', 'Luz'), ('Calibração', 'Calibração'), ('Base', 'Base')], max_length=30),
        ),
    ]
