# Generated by Django 3.0.5 on 2020-05-02 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CdC', '0018_auto_20200501_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlog',
            name='destino',
            field=models.CharField(choices=[('Patio', 'Patio'), ('Morumbi', 'Morumbi'), ('Butantã', 'Butantã'), ('Pinheiros', 'Pinheiros'), ('Faria Lima', 'Faria Lima'), ('Fradique Coutinho', 'Fradique Coutinho'), ('Oscar Freire', 'Oscar Freire'), ('Paulista', 'Paulista'), ('Higienopolis', 'Higienopolis'), ('Republica', 'Republica'), ('Luz', 'Luz'), ('Calibração', 'Calibração'), ('Em uso', 'Em uso')], max_length=30),
        ),
        migrations.AlterField(
            model_name='carlog',
            name='origem',
            field=models.CharField(choices=[('Patio', 'Patio'), ('Morumbi', 'Morumbi'), ('Butantã', 'Butantã'), ('Pinheiros', 'Pinheiros'), ('Faria Lima', 'Faria Lima'), ('Fradique Coutinho', 'Fradique Coutinho'), ('Oscar Freire', 'Oscar Freire'), ('Paulista', 'Paulista'), ('Higienopolis', 'Higienopolis'), ('Republica', 'Republica'), ('Luz', 'Luz'), ('Calibração', 'Calibração'), ('Em uso', 'Em uso')], max_length=30),
        ),
        migrations.AlterField(
            model_name='carlog',
            name='placa',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
