# Generated by Django 3.0.5 on 2020-05-03 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CdC', '0019_auto_20200501_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='type_of_log',
            field=models.IntegerField(null=True),
        ),
    ]
